version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: bruno
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: literatura_publica
    ports:
      - "5433:5432" # Use a porta 5433 no host para evitar conflito
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
